language: java
jdk:
- oraclejdk7
- openjdk7
before_script:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sleep 5
script:
 - mvn integration-test
after_success:
- mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: SJd6Y0qfRxVKXvJCXa0YPhwrXZW6gPDR2/EcDQ/4v1qedEmv7iX+CP2yLqqyTm3YQBZ7tNYLVtp4WaieIkU24nrpBM8Iq79CK/DI7nCVyxdM5GQsyUPP8vSKaX/m8siJuk67ZLS8D462brZK2odu/SM2dixD/FZ0VJHQQOct2Vy1gIpktMNoYOUVWq8ZTByMUzvvu0+nU87xuFtlVvIiKLx4l7+4bYaGwMrdh08bVIBjy0Jcqgnxz4pnh3uFc68Mv1Q/GF6iCct+iHUPgohsgp678oILd7iYMTPkhq3dN4a1Bin/+mRkixuLfiW6M8J/FzUqnEC7Vy9jCpEedQo/wzBKPUjGkgehMLwefCld+jQV+TIKxBQCxY0D/dNccTolGfVWrHYRUKYkO72a0gpy9f4jytFoDJGa76Mw+m4CbLXzG+08awAew91lTMd6OydUQPkDffOJkCfAB7jS9S4zWOs2FqoD+TIMrKJRVAVFndaA0ER9v4w/pijGMbEyDJk3uNxivSNMLWrVUxdt49WF00Cgd0Vs4rTArH3JZFoVXJGEzh5fWTsyw56W4t/hA+eIpbBLrhl6aFrhwudb8JO5Z/iJXQpBt8UdQ8RNrMMng3+D2k6GaUyK8gJouEdZCVz8AsRgvl5noNtWDMc0m38E+4Wgxoc/cgSvQySefr2sxQ8=
  app: citations-ohtu
  on:
    repo: KristianLauttamus/Ohtu-kki
